# Generated by Django 6.0.2 on 2026-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_city_order_comment_order_delivery_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='Україна', max_length=100, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вулиця, будинок, квартира'),
        ),
    ]
